version: "2"
services:
  back-end:
    image: u2668/node-js-sceleton
  web-presentation:
    image: u2668/web-presentation
    ports:
      - "80:80"
  chat-bot:
    image: u2668/chat-bot
  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command: ngrok http chat-bot:8080
