version: "2"
services:
  chatbot:
    image: u2668/chat-bot:with-gears
  ngrok:
    image: wernight/ngrok
    command: ngrok http -authtoken=3rx8CruDuurgPPfCmBz4w_4y17idRpwYodKBmQJ5JkC -subdomain=gotocanteenbot -log stdout chatbot:8080
  backend:
    image: "u2668/node-js-backend"
    environment:
      - CHAT_BOT_ENDPOINT=http://chatbot:8080/notifications
      - MONGO=mongodb://mongo:27017/
  mongo:
    image: mongo
